= Preparing for the lab

== Prerequisites

The attendees should fulfill following prerequisites:

* knowledge about Java and Java programming (JDK 8)
* basic knowledge about configuration management using Maven
* basic knowledge about Spring and Spring Boot

== Preparing the lab environment

=== Java Environment

You should be able to develop Java 8 application and build it using Maven. If you don't have actually such environment, please install following software:

* JDK 8 (http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[Oracle JDK] or https://developers.redhat.com/products/openjdk/download/[Red Hat OpenJDK])
* https://maven.apache.org/download.cgi[Maven]
* Your favourite Java IDE (https://www.jetbrains.com/idea/download/#section=windows[InteiJ CE] or https://www.eclipse.org/downloads/[Eclipse])

=== Docker Environment

During the lab we will use a local Docker environment provided by Docker Toolbox. Please https://docs.docker.com/v17.12/toolbox/toolbox_install_windows/[download] it and install following components

* VirtualBox (if you haven't installed it yet, required VirtualBox 5)
* Docker Client
* Docker Machine
* Docker Compose

After installation of the Toolbox:

* please create and configure the Docker Machine using following command
+
[source, bash]
----
docker-machine create --driver virtualbox --virtualbox-memory 6000 wks
----
* To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run:
+
[source, bash]
----
docker-machine env wks
----
* Next run the command from the last line of the output from the previous command
+
[source, bash]
----
@FOR /f "tokens=*" %i IN ('docker-machine env wks') DO @%i
----
* Check whether you can manage your Docker machine
+
[source, bash]
----
docker info
docker ps
----
* Pull the necessary Docker images (to avoid pulling during the workshop)
+
[source, bash]
----
docker pull spotify/kafka
docker pull mysql:8.0
docker pull openjdk:8-jre-alpine
docker pull mongo
docker images
----
* Shut down the Docker machine
+
[source, bash]
----
docker-machine stop wks
----


=== Other software

Install following additional software

* https://www.getpostman.com/apps[Postman]
* https://git-scm.com/download/win[Git for Windows] or any other git client

== Fork and clone the lab repositories

Plese create a GitHub account if you don't have it done yet. Please fork following repositories into your account

* https://github.com/xpaas-solutions/lab-microservices-in-practice-wks-2018
* https://github.com/xpaas-solutions/lab-microservices-in-practice-wks-2018-config

Next clone the both repositories into your notebook

[source, bash]
----
git clone https://github.com/<your-account>/lab-microservices-in-practice-wks-2018.git
git clone https://github.com/<your-account>/lab-microservices-in-practice-wks-2018-config.git
----

or if you use the ssh authentication

[source, bash]
----
git clone git@github.com:<your-account>/lab-microservices-in-practice-wks-2018.git
git clone git@github.com:<your-account>/lab-microservices-in-practice-wks-2018-config.git
----




